# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SamInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_string', models.CharField(max_length=256)),
                ('sequence_count', models.IntegerField(default=0)),
                ('sam_flag', models.IntegerField(default=0)),
                ('gene', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SamOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_count_out', models.IntegerField(default=0)),
                ('gene_out', models.CharField(max_length=128)),
                ('noMatch1_counts', models.IntegerField(default=0)),
                ('noMatch2_counts', models.IntegerField(default=0)),
                ('match_count', models.IntegerField(default=0)),
            ],
        ),
    ]
